read:
  - README.md
  - docs/AI_RULES.md
  - docs/CONVENTIONS.md
  - docs/ARCHITECTURE_INVENTORY.md
  - composer.lock
  - package-lock.json
  - docs/PR2_ROADMAP.md
  - docs/ENUMS.md
  - docs/DB_SCHEMA.md
  - database/migrations/
  - docs/UI_DESIGN.md
  - docs/architecture/README.yaml
