name: Decimal Quantity Math
type: Domain Rule
location:
  - docs/CONVENTIONS.md
purpose: Reference the canonical decimal quantity math requirements for inventory and purchasing.
when_to_use:
  - Any inventory-affecting calculations
  - Unit conversions and purchasing quantity math
when_not_to_use:
  - Calculations that do not involve quantity fields
rules:
  - The canonical requirements are defined in docs/CONVENTIONS.md.
  - Apply the canonical requirements wherever quantities are stored or calculated.
public_interface:
  - docs/CONVENTIONS.md
example_usage: |
  See docs/CONVENTIONS.md.
