name: InventoryCount
type: Eloquent Model
location:
  - app/Models/InventoryCount.php
purpose: Represent an inventory count session with status derived from posted_at.
when_to_use:
  - Recording inventory count sessions
  - Posting inventory count adjustments to the ledger
when_not_to_use:
  - Storing inventory adjustments without an inventory count context
rules:
  - Status is computed from posted_at and not stored in the database.
  - Posting must set posted_at and posted_by_user_id.
  - Enum-like values must use values defined in docs/ENUMS.md.
  - Tenant boundary is enforced when an authenticated user exists.
  - All quantity math uses BCMath with canonical scale matching stock_moves.quantity (scale = 6).
  - Quantities are represented as strings; never floats.
public_interface:
  - lines()
  - stockMoves()
  - getStatusAttribute()
example_usage: |
  $status = $inventoryCount->status;
