name: StockMove
type: Eloquent Model / Domain Rule
location:
  - app/Models/StockMove.php
purpose: Represent append-only inventory movements that form the inventory ledger.
when_to_use:
  - Any inventory-affecting operation such as receipts, issues, or adjustments
when_not_to_use:
  - Storing or mutating on-hand totals directly
rules:
  - Stock moves are append-only and must not be updated or deleted.
  - Quantity is signed and recorded in the item base UoM.
  - Enum-like values must use values defined in docs/ENUMS.md.
  - Tenant boundary is enforced when an authenticated user exists.
  - All quantity math uses BCMath with canonical scale matching stock_moves.quantity (scale = 6).
  - Quantities are represented as strings; never floats.
public_interface:
  - Item::stockMoves()
  - Item::onHandQuantity()
example_usage: |
  StockMove::create([
      'tenant_id' => $tenant->id,
      'item_id' => $item->id,
      'uom_id' => $item->base_uom_id,
      'quantity' => '10.000000',
      'type' => 'receipt',
  ]);
